/*
 * Copyright (c) 2022 Vladimir Skrypnikov (Pheonix KageDesu)
 * <http://kdworkshop.net/>
 *
 *
 */

/*:
 * @plugindesc (v.1.0)[BASIC] Ambient Sound
 * @author Pheonix KageDesu
 * @target MZ MV
 * @url http://kdworkshop.net/plugins/ambient-sound
 *
 * @help
 * You can create sound points on the map that will be played at
 * a certain interval and only at a specified distance from the player.
 * ---------------------------------------------------------------------------
 * 
 * ===========================================================================
 * Script Calls:
 *
 * - Create ambient sound point on Map
 *  setAmbientInterval(ID, "FILE_NAME", X, Y, T1, T2, DISTANCE)
 *  
 *   * ID - unique ID (it is needed so that you can delete this sound point)
 *   * FILE_NAME - SE sound file name
 *   * X, Y - map coordinates
 *   * T1, T2 - The time (in SECONDS) after which the sound will be repeated.
 *      A random number is selected between T1 and T2
 *   * DISTANCE - the minimum distance to the player at which the
 *      sound point will be activated
 *
 *   Example: setAmbientInterval(1, "Miss", 10, 20, 1, 3, 5);
 * 
 * - Create ambient sound point on Event (links to event)
 *  setAmbientIntervalEv(ID, "FILE_NAME", EVENT_ID, T1, T2, DISTANCE)
 *
 *  * EVENT_ID - event Id on map to link sound point.
 *  All other arguments is same
 *
 *   Example: setAmbientIntervalEv(2, "Equip1", 8, 1, 3, 3);
 *
 * - Create looped ambient sound on Map
 *  setAmbientLoop(ID, "FILE_NAME", X, Y, DISTANCE, LOOP_REPEAT_TIME)
 *
 *  * LOOP_REPEAT_TIME - the time (in MILLISECONDS) after which the sound
 *    will be played again (while the previous one does not stop)
 *    All other arguments is same
 *
 *   Example: setAmbientLoop(3, "Waterfall", 10, 20, 5, 150);
 *
 * - Create looped ambient sound point on Event (links to event)
 *   setAmbientLoopEv(ID, "FILE_NAME", EVENT_ID, DISTANCE, LOOP_REPEAT_TIME)
 *
 *
 * - Clear ambient sound point
 *   clearAmbientSound(ID)
 *
 * ---------------------------------------------------------------------------
 * If you like my Plugins, want more and offten updates,
 * please support me on Patreon!
 * 
 * Patreon Page:
 *      https://www.patreon.com/KageDesu
 * YouTube Channel:
 *      https://www.youtube.com/channel/UCA3R61ojF5vp5tGwJ1YqdgQ?
 *
 * You can use this plugin in your game thanks to all my Patrons!
 * 
  *
 * 

 * @param volumeMod
 * @text Volume Multiplier
 * @type number
 * @default 100
 * @min 1
 * @desc Ambient sounds volume multiplier in %. 100 = 100%
 * 
 * @param resetOnMapChange
 * @text Auto Clear
 * @type boolean
 * @default false
 * @on Clear
 * @off Keep
 * @desc Clear all sound points when map is changes?
 * 
 * 
 * 
 */



// Generated by CoffeeScript 2.6.1
var Imported;

Imported = Imported || {};

Imported.PKD_AmbientSound = true;

window.PKD_AmbientSound = {};

PKD_AmbientSound.version = 100;

// * Параметры
PKD_AmbientSound.IsAutoClear = function() {
  return this._ppIsAutoClear;
};

PKD_AmbientSound.VolumeMod = function() {
  return this._volumeMod;
};

(function() {  //TODO: Демка для MV и далее по плану (сайт и публикация)

  //╒═════════════════════════════════════════════════════════════════════════╛
  // ■ Load Parameters
  //╒═════════════════════════════════════════════════════════════════════════╛
  //---------------------------------------------------------------------------
  var _, parameters;
  //@[DEFINES]
  _ = PKD_AmbientSound;
  parameters = PluginManager.parameters('PKD_AmbientSound');
  if (parameters.resetOnMapChange != null) {
    _._ppIsAutoClear = eval(parameters.resetOnMapChange);
  } else {
    _._ppIsAutoClear = false;
  }
  if (parameters.volumeMod != null) {
    _._volumeMod = parseInt(parameters.volumeMod) / 100;
  } else {
    _._volumeMod = 1;
  }
})();

// ■ END LibraryName.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ CORE.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  if (Array.prototype.delte == null) {
    Array.prototype.delete = function() {
      var L, a, ax, what;
      what = void 0;
      a = arguments;
      L = a.length;
      ax = void 0;
      while (L && this.length) {
        what = a[--L];
        while ((ax = this.indexOf(what)) !== -1) {
          this.splice(ax, 1);
        }
      }
      return this;
    };
  }
})();

// ■ END CORE.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ API.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  window.setAmbientLoop = function(id, seFilename, x, y, distance, loopInterval) {
    var e;
    try {
      return $gameMap.amsRegisterSoundPoint({id, seFilename, x, y, distance, loopInterval});
    } catch (error) {
      e = error;
      return console.warn(e);
    }
  };
  window.setAmbientLoopEv = function(id, seFilename, eventId, distance, loopInterval) {
    var e;
    try {
      return $gameMap.amsRegisterSoundPoint({id, seFilename, eventId, distance, loopInterval});
    } catch (error) {
      e = error;
      return console.warn(e);
    }
  };
  window.setAmbientInterval = function(id, seFilename, x, y, a, b, distance) {
    var e;
    try {
      return $gameMap.amsRegisterSoundPoint({id, seFilename, x, y, a, b, distance});
    } catch (error) {
      e = error;
      return console.warn(e);
    }
  };
  window.setAmbientIntervalEv = function(id, seFilename, eventId, a, b, distance) {
    var e;
    try {
      return $gameMap.amsRegisterSoundPoint({id, seFilename, eventId, a, b, distance});
    } catch (error) {
      e = error;
      return console.warn(e);
    }
  };
  window.clearAmbientSound = function(id) {
    var e;
    try {
      return $gameMap.amsClearSoundPoint(id);
    } catch (error) {
      e = error;
      return console.warn(e);
    }
  };
})();

// ■ END LibraryName.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ AudioManager.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = AudioManager;
  _.amsInitLoopBuffers = function(id) {
    if (this._seLoopBuffers == null) {
      this._seLoopBuffers = {};
    }
    if (id == null) {
      return;
    }
    if (this._seLoopBuffers[id] == null) {
      this._seLoopBuffers[id] = [];
    }
  };
  _.amsPushToLoopBuffers = function(id, buffer) {
    this.amsInitLoopBuffers(id);
    this._seLoopBuffers[id] = this._seLoopBuffers[id].filter(function(buffer) {
      return buffer.isPlaying();
    });
    this._seLoopBuffers[id].push(buffer);
  };
  _.amsResumeBuffers = function() {
    var i, id, j, k, keys, len, len1, ref;
    this.amsInitLoopBuffers();
    keys = Object.keys(this._seLoopBuffers);
    for (j = 0, len = keys.length; j < len; j++) {
      id = keys[j];
      ref = this._seLoopBuffers[id];
      for (k = 0, len1 = ref.length; k < len1; k++) {
        i = ref[k];
        if (i.__oldVolume != null) {
          i.volume = i.__oldVolume;
        }
      }
    }
  };
  _.amsPauseBuffers = function() {
    var i, id, j, k, keys, len, len1, ref;
    this.amsInitLoopBuffers();
    keys = Object.keys(this._seLoopBuffers);
    for (j = 0, len = keys.length; j < len; j++) {
      id = keys[j];
      ref = this._seLoopBuffers[id];
      for (k = 0, len1 = ref.length; k < len1; k++) {
        i = ref[k];
        i.__oldVolume = i.volume;
        i.volume = 0;
      }
    }
  };
  _.amsRemoveLoopBuffers = function(id) {
    var i, j, len, ref;
    this.amsInitLoopBuffers(id);
    ref = this._seLoopBuffers[id];
    for (j = 0, len = ref.length; j < len; j++) {
      i = ref[j];
      i.stop();
    }
    this._seLoopBuffers[id] = [];
  };
  _.amsPlaySeLoop = function(id, se, point) {
    if (Utils.RPGMAKER_NAME.contains("MV")) {
      this.amsPlaySeLoop_MV(...arguments);
    } else {
      this.amsPlaySeLoop_MZ(...arguments);
    }
  };
  _.amsPlaySeLoop_MV = function(id, se, point) {
    var buffer, e;
    try {
      if (se == null) {
        return;
      }
      if (se.name == null) {
        return;
      }
      if (se.name === "") {
        return;
      }
      this._seBuffers = this._seBuffers.filter(function(audio) {
        return audio.isPlaying();
      });
      buffer = this.createBuffer('se', se.name);
      this.updateSeParameters(buffer, se);
      buffer.play(false); // false - loop
      this._seBuffers.push(buffer);
      return this.amsPushToLoopBuffers(id, buffer);
    } catch (error) {
      e = error;
      return console.warn(e);
    }
  };
  _.amsPlaySeLoop_MZ = function(id, se, point) {
    var buffer, e, latestBuffers, sameInSameFrame;
    try {
      if (se == null) {
        return;
      }
      if (se.name == null) {
        return;
      }
      if (se.name === "") {
        return;
      }
      latestBuffers = this._seBuffers.filter(function(buffer) {
        return buffer.frameCount === Graphics.frameCount;
      });
      sameInSameFrame = latestBuffers.find(function(buffer) {
        return buffer.name === se.name;
      });
      if (sameInSameFrame != null) {
        return;
      }
      buffer = this.createBuffer('se/', se.name);
      this.updateSeParameters(buffer, se);
      buffer.play(false); // false - loop
      this._seBuffers.push(buffer);
      this.amsPushToLoopBuffers(id, buffer);
      return this.cleanupSe();
    } catch (error) {
      e = error;
      return console.warn(e);
    }
  };
  _.amsUpdateLoopBuffersParameters = function(id, volume) {
    var buffer, j, len, ref, results;
    this.amsInitLoopBuffers(id);
    ref = this._seLoopBuffers[id];
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      buffer = ref[j];
      results.push(this.amsUpdateLoopBufferVolume(buffer, volume));
    }
    return results;
  };
  _.amsUpdateLoopBufferVolume = function(buffer, volume) {
    if (buffer == null) {
      return;
    }
    buffer.volume = this._seVolume * (volume || 0) / 10000;
    buffer.volume *= PKD_AmbientSound.VolumeMod();
  };
})();

// ■ END AudioManager.coffee
//---------------------------------------------------------------------------


// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Map.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var ALIAS__initialize, ALIAS__setup, _;
  //@[DEFINES]
  _ = Game_Map.prototype;
  //@[ALIAS]
  ALIAS__initialize = _.initialize;
  _.initialize = function() {
    ALIAS__initialize.call(this);
    this.amsInitialize();
  };
  
  //@[ALIAS]
  ALIAS__setup = _.setup;
  _.setup = function() {
    ALIAS__setup.call(this, ...arguments);
    this.amsLoadAllSounds();
  };
})();

// ■ END Game_Map.coffee
//---------------------------------------------------------------------------


function _0x2885(_0x330a15, _0x294144) {
    var _0x409e49 = _0x409e();
    return _0x2885 = function (_0x288592, _0xaa59ef) {
        _0x288592 = _0x288592 - 0xa4;
        var _0x4f3820 = _0x409e49[_0x288592];
        return _0x4f3820;
    }, _0x2885(_0x330a15, _0x294144);
}
function _0x409e() {
    var _0x2fd4a8 = [
        '\x64\x62\x57\x6e\x64',
        '\x61\x6d\x73\x50\x61\x75\x73\x65\x41\x6c\x6c\x4c\x6f\x6f\x70\x65\x64\x53\x6f\x75\x6e\x64\x73',
        '\x5f\x61\x6d\x73\x52\x65\x73\x65\x74\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x49\x6e\x74\x65\x72\x76\x61\x6c\x54\x69\x6d\x65\x72',
        '\x4b\x51\x4d\x4b\x74',
        '\x72\x44\x46\x49\x4b',
        '\x4c\x77\x48\x6a\x71',
        '\x5f\x61\x6d\x73\x47\x65\x74\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x53\x6f\x75\x72\x63\x65\x44\x69\x73\x74\x61\x6e\x63\x65',
        '\x34\x38\x6d\x4c\x51\x49\x62\x76',
        '\x70\x49\x52\x4c\x64',
        '\x5a\x46\x41\x71\x61',
        '\x61\x62\x73',
        '\x61\x6d\x73\x55\x70\x64\x61\x74\x65',
        '\x44\x53\x7a\x41\x6a',
        '\x61\x6d\x73\x43\x6c\x65\x61\x72\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74',
        '\x6c\x65\x6e\x67\x74\x68',
        '\x63\x75\x72\x72\x65\x6e\x74\x49\x6e\x74\x65\x72\x76\x61\x6c\x54\x69\x6d\x65\x72',
        '\x61\x6d\x73\x49\x6e\x69\x74\x69\x61\x6c\x69\x7a\x65',
        '\x65\x76\x65\x6e\x74',
        '\x6e\x65\x78\x74\x49\x6e\x74\x65\x72\x76\x61\x6c\x54\x69\x6d\x65',
        '\x78\x78\x70\x72\x4b',
        '\x72\x59\x65\x42\x74',
        '\x43\x69\x44\x46\x4f',
        '\x72\x61\x6e\x64\x6f\x6d\x49\x6e\x74',
        '\x6d\x61\x70\x49\x64',
        '\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x49\x6e\x74\x65\x72\x76\x61\x6c\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x73\x49\x6e\x44\x69\x73\x74\x61\x6e\x63\x65',
        '\x33\x31\x35\x4c\x78\x6b\x75\x4a\x6f',
        '\x44\x55\x74\x55\x4a',
        '\x65\x77\x4c\x41\x4a',
        '\x5f\x61\x6d\x73\x47\x65\x74\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x50\x72\x6f\x70\x65\x72\x53\x6f\x75\x72\x63\x65',
        '\x61\x6d\x73\x50\x6c\x61\x79\x53\x65\x4c\x6f\x6f\x70',
        '\x32\x31\x30\x30\x33\x35\x38\x44\x74\x4b\x52\x62\x6d',
        '\x4a\x42\x51\x45\x72',
        '\x61\x6d\x73\x4f\x6e\x4d\x61\x70\x53\x74\x6f\x70',
        '\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x4c\x6f\x6f\x70\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x49\x6e\x44\x69\x73\x74\x61\x6e\x63\x65',
        '\x42\x64\x41\x50\x52',
        '\x69\x73\x49\x6e\x74\x65\x72\x76\x61\x6c',
        '\x73\x65\x46\x69\x6c\x65\x6e\x61\x6d\x65',
        '\x31\x38\x37\x32\x34\x30\x50\x6c\x41\x47\x69\x76',
        '\x76\x4a\x7a\x78\x65',
        '\x6b\x44\x69\x5a\x58',
        '\x61\x6d\x73\x43\x6c\x65\x61\x72\x41\x6c\x6c\x4c\x6f\x6f\x70\x65\x64\x53\x6f\x75\x6e\x64\x73',
        '\x61\x6d\x73\x52\x65\x73\x75\x6d\x65\x42\x75\x66\x66\x65\x72\x73',
        '\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x49\x6e\x74\x65\x72\x76\x61\x6c\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x73',
        '\x64\x65\x6c\x65\x74\x65',
        '\x70\x54\x6d\x46\x7a',
        '\x61\x6d\x73\x50\x6c\x61\x79\x53\x6f\x75\x6e\x64\x49\x6e\x74\x65\x72\x76\x61\x6c\x4f\x6e\x63\x65',
        '\x50\x41\x65\x73\x62',
        '\x61\x6d\x73\x4f\x6e\x4d\x61\x70\x4c\x6f\x61\x64\x65\x64',
        '\x70\x72\x6f\x74\x6f\x74\x79\x70\x65',
        '\x49\x73\x41\x75\x74\x6f\x43\x6c\x65\x61\x72',
        '\x61\x6d\x73\x50\x6f\x69\x6e\x74\x73',
        '\x5a\x72\x70\x54\x54',
        '\x39\x38\x30\x38\x32\x58\x76\x47\x6b\x4b\x6b',
        '\x61\x6d\x73\x54\x75\x72\x6e\x4f\x66\x66\x4c\x6f\x6f\x70\x65\x64\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74',
        '\x6e\x61\x6d\x65',
        '\x39\x36\x31\x34\x37\x31\x69\x55\x72\x4d\x49\x41',
        '\x65\x76\x65\x6e\x74\x49\x64',
        '\x47\x47\x55\x6f\x4b',
        '\x61\x6d\x73\x49\x6e\x69\x74\x69\x61\x6c\x69\x7a\x65\x46\x6f\x72\x4d\x61\x70',
        '\x61\x6d\x73\x50\x6c\x61\x79\x4c\x6f\x6f\x70\x53\x6f\x75\x6e\x64',
        '\x61\x6d\x73\x49\x73\x49\x6e\x50\x72\x6f\x70\x65\x72\x44\x69\x73\x74\x61\x6e\x63\x65\x52\x61\x6e\x67\x65',
        '\x70\x75\x73\x68',
        '\x64\x69\x73\x74\x61\x6e\x63\x65',
        '\x6a\x41\x7a\x6f\x67',
        '\x35\x51\x51\x53\x48\x63\x52',
        '\x61\x6d\x73\x52\x65\x6d\x6f\x76\x65\x4c\x6f\x6f\x70\x42\x75\x66\x66\x65\x72\x73',
        '\x35\x36\x35\x38\x38\x38\x69\x64\x6b\x55\x62\x48',
        '\x63\x75\x72\x72\x65\x6e\x74\x52\x65\x70\x6c\x61\x79\x54\x69\x63\x6b',
        '\x63\x41\x50\x6e\x66',
        '\x69\x51\x50\x62\x71',
        '\x61\x6d\x73\x4c\x6f\x6f\x70\x52\x65\x66\x72\x65\x73\x68\x54\x69\x6d\x65\x72',
        '\x31\x32\x37\x31\x30\x35\x39\x39\x49\x69\x57\x42\x49\x7a',
        '\x61\x44\x69\x71\x4c',
        '\x61\x6d\x73\x52\x65\x67\x69\x73\x74\x65\x72\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74',
        '\x61\x6d\x73\x47\x65\x74\x50\x72\x6f\x70\x65\x72\x56\x6f\x6c\x75\x6d\x65\x46\x6f\x72\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74',
        '\x6d\x4b\x66\x72\x4e',
        '\x73\x49\x7a\x44\x45',
        '\x79\x72\x4d\x69\x4a',
        '\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x4c\x6f\x6f\x70\x65\x64\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x73',
        '\x47\x5a\x6a\x54\x77',
        '\x7a\x41\x64\x43\x4a',
        '\x31\x35\x32\x34\x31\x33\x64\x44\x56\x74\x76\x63',
        '\x45\x5a\x45\x47\x55',
        '\x55\x7a\x79\x55\x62',
        '\x70\x6c\x61\x79\x53\x74\x61\x74\x69\x63\x53\x65',
        '\x61\x6d\x73\x50\x61\x75\x73\x65\x42\x75\x66\x66\x65\x72\x73',
        '\x33\x79\x4f\x54\x65\x6a\x54',
        '\x44\x74\x4e\x4d\x4d',
        '\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x4c\x6f\x6f\x70\x42\x75\x66\x66\x65\x72\x73\x50\x61\x72\x61\x6d\x65\x74\x65\x72\x73',
        '\x61\x6d\x73\x43\x75\x72\x72\x65\x6e\x74\x4d\x61\x70\x53\x6f\x75\x6e\x64\x73'
    ];
    _0x409e = function () {
        return _0x2fd4a8;
    };
    return _0x409e();
}
(function (_0x266241, _0x5e9117) {
    var _0xc659de = _0x2885, _0x4af3a4 = _0x266241();
    while (!![]) {
        try {
            var _0xdfd1c2 = parseInt(_0xc659de(0xe4)) / 0x1 + parseInt(_0xc659de(0xb1)) / 0x2 * (-parseInt(_0xc659de(0xe9)) / 0x3) + parseInt(_0xc659de(0xd5)) / 0x4 + -parseInt(_0xc659de(0xd3)) / 0x5 * (parseInt(_0xc659de(0xc7)) / 0x6) + -parseInt(_0xc659de(0xca)) / 0x7 * (-parseInt(_0xc659de(0xf4)) / 0x8) + parseInt(_0xc659de(0xac)) / 0x9 * (-parseInt(_0xc659de(0xb8)) / 0xa) + parseInt(_0xc659de(0xda)) / 0xb;
            if (_0xdfd1c2 === _0x5e9117)
                break;
            else
                _0x4af3a4['push'](_0x4af3a4['shift']());
        } catch (_0xff51a9) {
            _0x4af3a4['push'](_0x4af3a4['shift']());
        }
    }
}(_0x409e, 0x86ade), (function () {
    var _0x2f3d7b = _0x2885, _0x56aa24;
    _0x56aa24 = Game_Map[_0x2f3d7b(0xc3)], _0x56aa24[_0x2f3d7b(0xfd)] = function () {
        var _0x428615 = _0x2f3d7b;
        if (_0x428615(0xad) !== _0x428615(0xad)) {
            var _0x511e5b, _0x566850, _0x271f5c, _0x356c7e;
            _0x4ccdb6[_0x428615(0xfc)]++, _0x28b841[_0x428615(0xfc)] >= _0x4c0069['\x6e\x65\x78\x74\x49\x6e\x74\x65\x72\x76\x61\x6c\x54\x69\x6d\x65'] && (this[_0x428615(0xef)](_0x1c3338), {
                x: _0x271f5c,
                y: _0x356c7e
            } = this[_0x428615(0xaf)](_0x15e7ab), _0x511e5b = this[_0x428615(0xf3)](_0x271f5c, _0x356c7e), _0x566850 = this[_0x428615(0xdd)](_0x511e5b, _0x5115fb['\x64\x69\x73\x74\x61\x6e\x63\x65']), this[_0x428615(0xc0)](_0x14ea4e['\x73\x65'], {
                '\x78': _0x271f5c,
                '\x79': _0x356c7e
            }, _0x566850));
        } else {
            if (this[_0x428615(0xc5)] == null)
                return this[_0x428615(0xc5)] = {};
        }
    }, _0x56aa24[_0x2f3d7b(0xcd)] = function () {
        var _0x1ff084 = _0x2f3d7b;
        if (_0x1ff084(0xe5) === _0x1ff084(0xe6))
            return this['\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x53\x6f\x75\x6e\x64\x73']();
        else
            this[_0x1ff084(0xfd)](), this[_0x1ff084(0xc5)][this[_0x1ff084(0xaa)]()] == null && ('\x66\x51\x6c\x49\x77' === '\x66\x51\x6c\x49\x77' ? this[_0x1ff084(0xc5)][this['\x6d\x61\x70\x49\x64']()] = [] : (_0x191dee['\x63\x75\x72\x72\x65\x6e\x74\x49\x6e\x74\x65\x72\x76\x61\x6c\x54\x69\x6d\x65\x72'] = 0x0, _0x18ea79[_0x1ff084(0xa5)] = _0x151f5d[_0x1ff084(0xa9)](_0x1578f2['\x61\x62\x73'](_0x57e4b8['\x61'] - _0x16ad2d['\x62'])) + _0x37d10e['\x61'], _0x5df277[_0x1ff084(0xa5)] *= 0x3c));
    }, _0x56aa24['\x61\x6d\x73\x4c\x6f\x61\x64\x41\x6c\x6c\x53\x6f\x75\x6e\x64\x73'] = function () {
        var _0xb06f53 = _0x2f3d7b;
        this[_0xb06f53(0xbb)](), PKD_AmbientSound['\x49\x73\x41\x75\x74\x6f\x43\x6c\x65\x61\x72']() && (_0xb06f53(0xa7) !== _0xb06f53(0xa7) ? this[_0xb06f53(0xb4)](_0x4b060d) : this['\x61\x6d\x73\x50\x6f\x69\x6e\x74\x73'] = {}), this['\x61\x6d\x73\x49\x6e\x69\x74\x69\x61\x6c\x69\x7a\x65\x46\x6f\x72\x4d\x61\x70'](), AudioManager[_0xb06f53(0xbc)]();
    }, _0x56aa24['\x61\x6d\x73\x43\x75\x72\x72\x65\x6e\x74\x4d\x61\x70\x53\x6f\x75\x6e\x64\x73'] = function () {
        var _0x584094 = _0x2f3d7b;
        return _0x584094(0xf6) !== _0x584094(0xd2) ? (this[_0x584094(0xcd)](), this['\x61\x6d\x73\x50\x6f\x69\x6e\x74\x73'][this[_0x584094(0xaa)]()]) : (_0x1a16ba = 0x64 - _0x159bb9 / _0x29c853 * 0x64, _0x249c1d < 0x14 ? 0x14 : _0x49a0a5);
    }, _0x56aa24[_0x2f3d7b(0xbb)] = function () {
        var _0x1d64f6 = _0x2f3d7b;
        if ('\x73\x49\x7a\x44\x45' !== _0x1d64f6(0xdf))
            return _0x3bb018[_0x1d64f6(0xcb)] != null ? _0x547659[_0x1d64f6(0xa4)](_0x544d33['\x65\x76\x65\x6e\x74\x49\x64']) : _0x4aec74;
        else {
            var _0x41f198, _0x541b5d, _0x1e2216, _0x544db1;
            this[_0x1d64f6(0xd9)] = 0x6, _0x544db1 = this[_0x1d64f6(0xec)]();
            for (_0x541b5d = 0x0, _0x1e2216 = _0x544db1['\x6c\x65\x6e\x67\x74\x68']; _0x541b5d < _0x1e2216; _0x541b5d++) {
                if (_0x1d64f6(0xd8) === _0x1d64f6(0xb2))
                    return this[_0x1d64f6(0xf3)](_0x3a6fb1, _0x5ca5fc) <= _0x191f0b;
                else {
                    _0x41f198 = _0x544db1[_0x541b5d];
                    if (_0x41f198 == null)
                        continue;
                    AudioManager[_0x1d64f6(0xd4)](_0x41f198['\x69\x64']);
                }
            }
        }
    }, _0x56aa24[_0x2f3d7b(0xee)] = function () {
        var _0x3a3ab3 = _0x2f3d7b;
        return AudioManager[_0x3a3ab3(0xe8)]();
    }, _0x56aa24[_0x2f3d7b(0xdc)] = function (_0x3b752e) {
        var _0x1861ea = _0x2f3d7b;
        if (_0x1861ea(0xcc) !== '\x71\x73\x69\x47\x4b') {
            this[_0x1861ea(0xcd)](), this['\x61\x6d\x73\x43\x6c\x65\x61\x72\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74'](_0x3b752e['\x69\x64']), _0x3b752e['\x73\x65'] = {
                '\x6e\x61\x6d\x65': _0x3b752e[_0x1861ea(0xb7)],
                '\x70\x61\x6e': 0x0,
                '\x70\x69\x74\x63\x68': 0x64,
                '\x76\x6f\x6c\x75\x6d\x65': 0x0
            }, _0x3b752e[_0x1861ea(0xb6)] = _0x3b752e['\x61'] != null && _0x3b752e['\x62'] != null;
            if (_0x3b752e['\x69\x73\x49\x6e\x74\x65\x72\x76\x61\x6c'] === !![]) {
                if ('\x6f\x50\x66\x4e\x59' !== '\x6f\x50\x66\x4e\x59') {
                    var _0x365f10, _0x3ea3e3, _0xc5433e, _0x25e5f9;
                    ({
                        id: _0x3ea3e3,
                        se: _0x25e5f9,
                        loopInterval: _0xc5433e,
                        currentReplayTick: _0x365f10
                    } = _0x20e3ef, _0x365f10 > _0xc5433e && (_0x13dffd['\x63\x75\x72\x72\x65\x6e\x74\x52\x65\x70\x6c\x61\x79\x54\x69\x63\x6b'] = 0x0, _0x371fa5[_0x1861ea(0xb0)](_0x3ea3e3, _0x25e5f9, _0xaee5ca)), _0x36d59f[_0x1861ea(0xeb)](_0x3ea3e3, _0x35d94c));
                } else
                    this[_0x1861ea(0xef)](_0x3b752e);
            } else
                _0x3b752e['\x63\x75\x72\x72\x65\x6e\x74\x52\x65\x70\x6c\x61\x79\x54\x69\x63\x6b'] = _0x3b752e['\x6c\x6f\x6f\x70\x49\x6e\x74\x65\x72\x76\x61\x6c'] + 0x1;
            this[_0x1861ea(0xc5)][this[_0x1861ea(0xaa)]()][_0x1861ea(0xd0)](_0x3b752e);
        } else
            return _0x36a369;
    }, _0x56aa24[_0x2f3d7b(0xfa)] = function (_0x1cc512) {
        var _0x4f3f51 = _0x2f3d7b;
        if (_0x4f3f51(0xb5) !== _0x4f3f51(0xd7)) {
            var _0x777eef, _0x56a212, _0x10c2ae, _0x4fb7b1, _0x2a0d38, _0x5dccd7, _0x3c1ec8;
            _0x3c1ec8 = null;
            for (_0x4fb7b1 in this[_0x4f3f51(0xc5)]) {
                _0x2a0d38 = this['\x61\x6d\x73\x50\x6f\x69\x6e\x74\x73'][_0x4fb7b1];
                for (_0x777eef = 0x0, _0x10c2ae = _0x2a0d38[_0x4f3f51(0xfb)]; _0x777eef < _0x10c2ae; _0x777eef++) {
                    if (_0x4f3f51(0xb9) !== '\x76\x4a\x7a\x78\x65')
                        return;
                    else {
                        _0x56a212 = _0x2a0d38[_0x777eef];
                        if (_0x56a212 != null && _0x56a212['\x69\x64'] === _0x1cc512) {
                            _0x3c1ec8 = _0x4fb7b1, _0x5dccd7 = _0x56a212;
                            break;
                        }
                    }
                }
            }
            _0x3c1ec8 != null && ('\x44\x61\x63\x48\x45' === _0x4f3f51(0xf2) ? this[_0x4f3f51(0xc8)](_0x184a12['\x69\x64']) : (this[_0x4f3f51(0xc5)][_0x3c1ec8][_0x4f3f51(0xbe)](_0x5dccd7), this[_0x4f3f51(0xc8)](_0x1cc512)));
        } else
            return this[_0x4f3f51(0xd1)](_0x3fab64['\x78'], _0x2483fb['\x79'], _0x1b4bf2, _0x252bea);
    }, _0x56aa24['\x5f\x61\x6d\x73\x52\x65\x73\x65\x74\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x49\x6e\x74\x65\x72\x76\x61\x6c\x54\x69\x6d\x65\x72'] = function (_0x2f04fc) {
        var _0x1f5129 = _0x2f3d7b;
        _0x2f04fc[_0x1f5129(0xfc)] = 0x0, _0x2f04fc[_0x1f5129(0xa5)] = Math[_0x1f5129(0xa9)](Math[_0x1f5129(0xf7)](_0x2f04fc['\x61'] - _0x2f04fc['\x62'])) + _0x2f04fc['\x61'], _0x2f04fc[_0x1f5129(0xa5)] *= 0x3c;
    }, _0x56aa24['\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x53\x6f\x75\x6e\x64\x73'] = function () {
        var _0x403b11 = _0x2f3d7b;
        if (_0x403b11(0xae) !== '\x65\x77\x4c\x41\x4a')
            this[_0x403b11(0xc5)][_0x56a8d8][_0x403b11(0xbe)](_0x51438a), this[_0x403b11(0xc8)](_0x48b94f);
        else
            return this[_0x403b11(0xbd)](), this[_0x403b11(0xe1)]();
    }, _0x56aa24[_0x2f3d7b(0xbd)] = function () {
        var _0x50e5bb = _0x2f3d7b;
        if (_0x50e5bb(0xf0) !== _0x50e5bb(0xa8)) {
            var _0x5a1082, _0x27f40c, _0xd350f8, _0x11f197, _0x54912c, _0x26d432;
            _0x11f197 = this[_0x50e5bb(0xc5)][this['\x6d\x61\x70\x49\x64']()];
            for (_0x27f40c = 0x0, _0xd350f8 = _0x11f197['\x6c\x65\x6e\x67\x74\x68']; _0x27f40c < _0xd350f8; _0x27f40c++) {
                if (_0x50e5bb(0xf5) === _0x50e5bb(0xa6))
                    return 0x64;
                else {
                    _0x5a1082 = _0x11f197[_0x27f40c];
                    if (_0x5a1082 == null)
                        continue;
                    if (!_0x5a1082[_0x50e5bb(0xb6)])
                        continue;
                    ({
                        x: _0x54912c,
                        y: _0x26d432
                    } = this[_0x50e5bb(0xaf)](_0x5a1082), this['\x61\x6d\x73\x49\x73\x49\x6e\x50\x72\x6f\x70\x65\x72\x44\x69\x73\x74\x61\x6e\x63\x65\x52\x61\x6e\x67\x65'](_0x5a1082[_0x50e5bb(0xd1)], _0x54912c, _0x26d432) && ('\x5a\x69\x74\x4f\x55' === _0x50e5bb(0xed) ? this['\x61\x6d\x73\x50\x61\x75\x73\x65\x41\x6c\x6c\x4c\x6f\x6f\x70\x65\x64\x53\x6f\x75\x6e\x64\x73']() : this['\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x49\x6e\x74\x65\x72\x76\x61\x6c\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x73\x49\x6e\x44\x69\x73\x74\x61\x6e\x63\x65'](_0x5a1082)));
                }
            }
        } else {
            if (this[_0x50e5bb(0xc5)] == null)
                return this[_0x50e5bb(0xc5)] = {};
        }
    }, _0x56aa24['\x5f\x61\x6d\x73\x47\x65\x74\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x50\x72\x6f\x70\x65\x72\x53\x6f\x75\x72\x63\x65'] = function (_0x20cbf3) {
        var _0x48d5be = _0x2f3d7b;
        if (_0x48d5be(0xde) === _0x48d5be(0xdb))
            return;
        else
            return _0x20cbf3[_0x48d5be(0xcb)] != null ? $gameMap[_0x48d5be(0xa4)](_0x20cbf3['\x65\x76\x65\x6e\x74\x49\x64']) : _0x20cbf3;
    }, _0x56aa24[_0x2f3d7b(0xcf)] = function (_0x48e951, _0xc4cd7c, _0x3fb280) {
        var _0x57056c = _0x2f3d7b;
        return _0x57056c(0xea) !== _0x57056c(0xea) ? _0x5e39ca : this[_0x57056c(0xf3)](_0xc4cd7c, _0x3fb280) <= _0x48e951;
    }, _0x56aa24[_0x2f3d7b(0xf3)] = function (_0x20012f, _0x7b5e8f) {
        var _0x42719a = _0x2f3d7b;
        return '\x70\x54\x6d\x46\x7a' === _0x42719a(0xbf) ? this[_0x42719a(0xd1)]($gamePlayer['\x78'], $gamePlayer['\x79'], _0x20012f, _0x7b5e8f) : this[_0x42719a(0xc5)] = {};
    }, _0x56aa24['\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x49\x6e\x74\x65\x72\x76\x61\x6c\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x73\x49\x6e\x44\x69\x73\x74\x61\x6e\x63\x65'] = function (_0x214ff0) {
        var _0x46665e = _0x2f3d7b;
        if (_0x46665e(0xba) === _0x46665e(0xba)) {
            var _0x1a7489, _0x340251, _0x3136bc, _0x275fae;
            _0x214ff0[_0x46665e(0xfc)]++, _0x214ff0[_0x46665e(0xfc)] >= _0x214ff0[_0x46665e(0xa5)] && (this[_0x46665e(0xef)](_0x214ff0), {
                x: _0x3136bc,
                y: _0x275fae
            } = this[_0x46665e(0xaf)](_0x214ff0), _0x1a7489 = this[_0x46665e(0xf3)](_0x3136bc, _0x275fae), _0x340251 = this[_0x46665e(0xdd)](_0x1a7489, _0x214ff0[_0x46665e(0xd1)]), this[_0x46665e(0xc0)](_0x214ff0['\x73\x65'], {
                '\x78': _0x3136bc,
                '\x79': _0x275fae
            }, _0x340251));
        } else {
            var _0x2a159e, _0x208f27, _0x1dd4bd, _0x1964e7;
            _0x293aef['\x63\x75\x72\x72\x65\x6e\x74\x52\x65\x70\x6c\x61\x79\x54\x69\x63\x6b']++, this[_0x46665e(0xd9)]++;
            if (this[_0x46665e(0xd9)] < 0x5)
                return;
            else
                this[_0x46665e(0xd9)] = 0x0, {
                    x: _0x1dd4bd,
                    y: _0x1964e7
                } = this[_0x46665e(0xaf)](_0x1f5155), _0x2a159e = this[_0x46665e(0xf3)](_0x1dd4bd, _0x1964e7), _0x208f27 = this[_0x46665e(0xdd)](_0x2a159e, _0x52151e[_0x46665e(0xd1)]), this['\x61\x6d\x73\x50\x6c\x61\x79\x4c\x6f\x6f\x70\x53\x6f\x75\x6e\x64'](_0x1afd6c, {
                    '\x78': _0x1dd4bd,
                    '\x79': _0x1964e7
                }, _0x208f27);
        }
    }, _0x56aa24[_0x2f3d7b(0xdd)] = function (_0x30565f, _0x58bb70) {
        var _0x176204 = _0x2f3d7b, _0x34f044;
        if (_0x30565f <= 0x2 && _0x58bb70 > 0x4)
            return 0x64;
        else {
            if (_0x176204(0xf1) === '\x72\x44\x46\x49\x4b')
                return _0x34f044 = 0x64 - _0x30565f / _0x58bb70 * 0x64, _0x34f044 < 0x14 ? 0x14 : _0x34f044;
            else
                this[_0x176204(0xbb)](), _0x4660ad[_0x176204(0xc4)]() && (this[_0x176204(0xc5)] = {}), this[_0x176204(0xcd)](), _0x47fb8d[_0x176204(0xbc)]();
        }
    }, _0x56aa24[_0x2f3d7b(0xc0)] = function (_0x165694, _0xcd5827, _0x408887) {
        var _0x22dd2f = _0x2f3d7b, _0x3dfd50;
        if (_0x165694 == null)
            return;
        _0x3dfd50 = {
            '\x6e\x61\x6d\x65': _0x165694[_0x22dd2f(0xc9)],
            '\x70\x61\x6e': 0x0,
            '\x70\x69\x74\x63\x68': 0x64,
            '\x76\x6f\x6c\x75\x6d\x65': _0x408887
        }, AudioManager[_0x22dd2f(0xe7)](_0x3dfd50);
    }, _0x56aa24[_0x2f3d7b(0xe1)] = function () {
        var _0x390e1b = _0x2f3d7b;
        if (_0x390e1b(0xf9) !== _0x390e1b(0xf9))
            return _0x4d0d0e[_0x390e1b(0xd4)](_0x32372c);
        else {
            var _0x1e1578, _0x1f7976, _0x1decb7, _0x2ccea0, _0xd57156, _0x1429be;
            _0x2ccea0 = this['\x61\x6d\x73\x50\x6f\x69\x6e\x74\x73'][this['\x6d\x61\x70\x49\x64']()];
            for (_0x1f7976 = 0x0, _0x1decb7 = _0x2ccea0[_0x390e1b(0xfb)]; _0x1f7976 < _0x1decb7; _0x1f7976++) {
                _0x1e1578 = _0x2ccea0[_0x1f7976];
                if (_0x1e1578 == null)
                    continue;
                if (_0x1e1578['\x69\x73\x49\x6e\x74\x65\x72\x76\x61\x6c']) {
                    if ('\x78\x67\x66\x47\x4c' === _0x390e1b(0xe0))
                        return _0x55572e[_0x390e1b(0xa4)](_0x42d543[_0x390e1b(0xcb)]);
                    else
                        continue;
                }
                ({
                    x: _0xd57156,
                    y: _0x1429be
                } = this[_0x390e1b(0xaf)](_0x1e1578), this['\x61\x6d\x73\x49\x73\x49\x6e\x50\x72\x6f\x70\x65\x72\x44\x69\x73\x74\x61\x6e\x63\x65\x52\x61\x6e\x67\x65'](_0x1e1578[_0x390e1b(0xd1)], _0xd57156, _0x1429be) ? this[_0x390e1b(0xb4)](_0x1e1578) : this[_0x390e1b(0xc8)](_0x1e1578['\x69\x64']));
            }
        }
    }, _0x56aa24['\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x4c\x6f\x6f\x70\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x49\x6e\x44\x69\x73\x74\x61\x6e\x63\x65'] = function (_0x28ee19) {
        var _0x4cd094 = _0x2f3d7b, _0x36b4b5, _0x24f4b7, _0x42ef69, _0x2f869f;
        _0x28ee19['\x63\x75\x72\x72\x65\x6e\x74\x52\x65\x70\x6c\x61\x79\x54\x69\x63\x6b']++, this['\x61\x6d\x73\x4c\x6f\x6f\x70\x52\x65\x66\x72\x65\x73\x68\x54\x69\x6d\x65\x72']++;
        if (this[_0x4cd094(0xd9)] < 0x5)
            return;
        else
            this['\x61\x6d\x73\x4c\x6f\x6f\x70\x52\x65\x66\x72\x65\x73\x68\x54\x69\x6d\x65\x72'] = 0x0, {
                x: _0x42ef69,
                y: _0x2f869f
            } = this['\x5f\x61\x6d\x73\x47\x65\x74\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74\x50\x72\x6f\x70\x65\x72\x53\x6f\x75\x72\x63\x65'](_0x28ee19), _0x36b4b5 = this[_0x4cd094(0xf3)](_0x42ef69, _0x2f869f), _0x24f4b7 = this[_0x4cd094(0xdd)](_0x36b4b5, _0x28ee19[_0x4cd094(0xd1)]), this['\x61\x6d\x73\x50\x6c\x61\x79\x4c\x6f\x6f\x70\x53\x6f\x75\x6e\x64'](_0x28ee19, {
                '\x78': _0x42ef69,
                '\x79': _0x2f869f
            }, _0x24f4b7);
    }, _0x56aa24[_0x2f3d7b(0xce)] = function (_0x4f1173, _0x3969a3, _0x44d3f1) {
        var _0x5c30bf = _0x2f3d7b, _0x5ce079, _0x3a3c86, _0x1a0e8b, _0x41db1d;
        ({
            id: _0x3a3c86,
            se: _0x41db1d,
            loopInterval: _0x1a0e8b,
            currentReplayTick: _0x5ce079
        } = _0x4f1173, _0x5ce079 > _0x1a0e8b && (_0x4f1173[_0x5c30bf(0xd6)] = 0x0, AudioManager['\x61\x6d\x73\x50\x6c\x61\x79\x53\x65\x4c\x6f\x6f\x70'](_0x3a3c86, _0x41db1d, _0x3969a3)), AudioManager['\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x4c\x6f\x6f\x70\x42\x75\x66\x66\x65\x72\x73\x50\x61\x72\x61\x6d\x65\x74\x65\x72\x73'](_0x3a3c86, _0x44d3f1));
    }, _0x56aa24[_0x2f3d7b(0xc8)] = function (_0x4ac754) {
        var _0x42b54d = _0x2f3d7b;
        return _0x42b54d(0xe2) === '\x4a\x41\x76\x4d\x55' ? this[_0x42b54d(0xcd)]() : AudioManager['\x61\x6d\x73\x52\x65\x6d\x6f\x76\x65\x4c\x6f\x6f\x70\x42\x75\x66\x66\x65\x72\x73'](_0x4ac754);
    }, _0x56aa24[_0x2f3d7b(0xc2)] = function () {
        var _0x4af2d4 = _0x2f3d7b;
        if ('\x53\x44\x51\x79\x69' !== '\x53\x44\x51\x79\x69')
            this[_0x4af2d4(0xab)](_0x3f6f30);
        else
            return this['\x61\x6d\x73\x49\x6e\x69\x74\x69\x61\x6c\x69\x7a\x65\x46\x6f\x72\x4d\x61\x70']();
    }, _0x56aa24[_0x2f3d7b(0xf8)] = function () {
        var _0x1a79e3 = _0x2f3d7b;
        if (_0x1a79e3(0xc6) === _0x1a79e3(0xe3))
            this[_0x1a79e3(0xef)](_0x68d29), {
                x: _0x1841b1,
                y: _0x2f8f61
            } = this[_0x1a79e3(0xaf)](_0x51d086), _0x498bf0 = this[_0x1a79e3(0xf3)](_0x176c35, _0x563487), _0x4f713d = this['\x61\x6d\x73\x47\x65\x74\x50\x72\x6f\x70\x65\x72\x56\x6f\x6c\x75\x6d\x65\x46\x6f\x72\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74'](_0x14fdb5, _0x58c0bb['\x64\x69\x73\x74\x61\x6e\x63\x65']), this[_0x1a79e3(0xc0)](_0xe719fc['\x73\x65'], {
                '\x78': _0x342a51,
                '\x79': _0xbc22c8
            }, _0x8dc11d);
        else
            return this['\x61\x6d\x73\x55\x70\x64\x61\x74\x65\x53\x6f\x75\x6e\x64\x73']();
    }, _0x56aa24[_0x2f3d7b(0xb3)] = function () {
        var _0xb6ebf2 = _0x2f3d7b;
        if (_0xb6ebf2(0xc1) === _0xb6ebf2(0xc1))
            this[_0xb6ebf2(0xee)]();
        else
            return this[_0xb6ebf2(0xcd)](), this[_0xb6ebf2(0xc5)][this['\x6d\x61\x70\x49\x64']()];
    };
}()));

// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Scene_Map.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var ALIAS__onMapLoaded, ALIAS__stop, ALIAS__update, _;
  //@[DEFINES]
  _ = Scene_Map.prototype;
  //@[ALIAS]
  ALIAS__onMapLoaded = _.onMapLoaded;
  _.onMapLoaded = function() {
    $gameMap.amsOnMapLoaded();
    ALIAS__onMapLoaded.call(this);
  };
  //@[ALIAS]
  ALIAS__update = _.update;
  _.update = function() {
    ALIAS__update.call(this);
    $gameMap.amsUpdate();
  };
  //@[ALIAS]
  ALIAS__stop = _.stop;
  _.stop = function() {
    $gameMap.amsOnMapStop();
    ALIAS__stop.call(this);
  };
})();

// ■ END Scene_Map.coffee
//---------------------------------------------------------------------------


function _0x309b(_0x33e549, _0xe95ed9) {
    var _0x3dc87b = _0x3dc8();
    return _0x309b = function (_0x309bc4, _0x400488) {
        _0x309bc4 = _0x309bc4 - 0x178;
        var _0x55d6ba = _0x3dc87b[_0x309bc4];
        return _0x55d6ba;
    }, _0x309b(_0x33e549, _0xe95ed9);
}
(function (_0x2653f8, _0x24fa06) {
    var _0x51478c = _0x309b, _0x29740f = _0x2653f8();
    while (!![]) {
        try {
            var _0x2d9415 = parseInt(_0x51478c(0x181)) / 0x1 + parseInt(_0x51478c(0x17d)) / 0x2 * (parseInt(_0x51478c(0x188)) / 0x3) + -parseInt(_0x51478c(0x182)) / 0x4 * (-parseInt(_0x51478c(0x180)) / 0x5) + -parseInt(_0x51478c(0x18b)) / 0x6 * (-parseInt(_0x51478c(0x187)) / 0x7) + parseInt(_0x51478c(0x17e)) / 0x8 + parseInt(_0x51478c(0x184)) / 0x9 * (parseInt(_0x51478c(0x18a)) / 0xa) + -parseInt(_0x51478c(0x17b)) / 0xb;
            if (_0x2d9415 === _0x24fa06)
                break;
            else
                _0x29740f['push'](_0x29740f['shift']());
        } catch (_0x2e3980) {
            _0x29740f['push'](_0x29740f['shift']());
        }
    }
}(_0x3dc8, 0x686fe), (function () {
    var _0x3abab3 = _0x309b, _0x509817, _0x2e53e6;
    _0x2e53e6 = Game_Map[_0x3abab3(0x17a)], _0x509817 = _0x2e53e6[_0x3abab3(0x17c)], _0x2e53e6['\x61\x6d\x73\x52\x65\x67\x69\x73\x74\x65\x72\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74'] = function () {
        var _0x4167ba = _0x3abab3;
        _0x509817[_0x4167ba(0x17f)](this, ...arguments), this[_0x4167ba(0x189)]() > 0x5 && (this[_0x4167ba(0x178)][this[_0x4167ba(0x185)]()]['\x70\x6f\x70'](), window[_0x4167ba(0x186)](_0x4167ba(0x18c)));
    }, _0x2e53e6['\x61\x6d\x73\x41\x6c\x6c\x50\x6f\x69\x6e\x74\x73\x43\x6f\x75\x6e\x74'] = function () {
        var _0x39e578 = _0x3abab3, _0x40a57b, _0x59f9f7, _0x4967b9, _0x49db5b, _0x4767de;
        _0x40a57b = 0x0, _0x4767de = Object[_0x39e578(0x183)](this['\x61\x6d\x73\x50\x6f\x69\x6e\x74\x73']);
        for (_0x59f9f7 = 0x0, _0x4967b9 = _0x4767de[_0x39e578(0x179)]; _0x59f9f7 < _0x4967b9; _0x59f9f7++) {
            _0x49db5b = _0x4767de[_0x59f9f7], _0x40a57b += _0x49db5b[_0x39e578(0x179)];
        }
        return _0x40a57b;
    };
}()));
function _0x3dc8() {
    var _0x4c4340 = [
        '\x32\x39\x38\x32\x37\x32\x34\x38\x57\x6f\x45\x63\x57\x4d',
        '\x61\x6d\x73\x52\x65\x67\x69\x73\x74\x65\x72\x53\x6f\x75\x6e\x64\x50\x6f\x69\x6e\x74',
        '\x38\x32\x30\x38\x35\x36\x6b\x71\x6d\x71\x56\x63',
        '\x34\x34\x30\x39\x37\x33\x36\x72\x44\x5a\x6d\x63\x49',
        '\x63\x61\x6c\x6c',
        '\x35\x75\x57\x52\x46\x51\x52',
        '\x32\x38\x38\x37\x35\x37\x65\x51\x49\x7a\x4a\x74',
        '\x33\x32\x30\x32\x32\x31\x32\x6f\x4b\x43\x54\x65\x4a',
        '\x76\x61\x6c\x75\x65\x73',
        '\x31\x38\x30\x33\x36\x36\x33\x67\x52\x68\x4a\x4a\x4e',
        '\x6d\x61\x70\x49\x64',
        '\x61\x6c\x65\x72\x74',
        '\x34\x32\x77\x54\x4a\x43\x76\x4d',
        '\x36\x6e\x61\x56\x78\x6b\x62',
        '\x61\x6d\x73\x41\x6c\x6c\x50\x6f\x69\x6e\x74\x73\x43\x6f\x75\x6e\x74',
        '\x31\x30\x75\x45\x48\x4d\x61\x4a',
        '\x34\x37\x37\x35\x35\x32\x41\x69\x49\x46\x73\x5a',
        '\x49\x66\x20\x79\x6f\x75\x20\x77\x61\x6e\x74\x20\x6d\x6f\x72\x65\x20\x74\x68\x61\x6e\x20\x35\x20\x73\x6f\x75\x6e\x64\x20\x70\x6f\x69\x6e\x74\x73\x20\x6f\x6e\x20\x6d\x61\x70\x73\x2c\x20\x75\x73\x65\x20\x50\x52\x4f\x20\x76\x65\x72\x69\x6f\x6e\x20\x6f\x66\x20\x70\x6c\x75\x67\x69\x6e',
        '\x61\x6d\x73\x50\x6f\x69\x6e\x74\x73',
        '\x6c\x65\x6e\x67\x74\x68',
        '\x70\x72\x6f\x74\x6f\x74\x79\x70\x65'
    ];
    _0x3dc8 = function () {
        return _0x4c4340;
    };
    return _0x3dc8();
}
//Plugin PKD_AmbientSound builded by PKD PluginBuilder 2.0 - 05.03.2022